#!/bin/sh 
# udhcpc 获取IPTV网口或释放IP时会调用此脚本，用于配置或清理IP、route、iptables、重启udpxy等
# 优先启动rtp2httpd(可执行文件存放于/koolshare/bin/或者/koolshare/scripts目录);没有rtp2httpd则尝试启动udpxy.监听br0,4022端口

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

logger -st "($(basename $0))" $$ "event: $1"

[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

startIf_udpxy() {
  mcastInterface="$1"
  # 未安装 udpxy 直接返回
  if ! which udpxy >/dev/null 2>&1; then
    return 1
  fi
  # 查找并杀掉已存在的 udpxy 进程（同接口）
  pidof udpxy | xargs -r kill -9
  # 启动 udpxy
  udpxy -m "$mcastInterface" -p 4022 -B 2Mb -a br0
  # 记录日志
  logger -st "($(basename "$0"))" $$ "udpxy started($mcastInterface)"
  return 0
}

startIf_rtp2httpd() {
  mcastInterface="$1"
  # 未安装 rtp2httpd 直接返回
  if ! which rtp2httpd >/dev/null 2>&1; then
    return 1
  fi
  # 查找并杀掉已存在的 rtp2httpd 进程（同接口）
  pidof rtp2httpd | xargs -r kill -9
  # 启动 rtp2httpd
  nohup rtp2httpd --noconfig --listen 4022 --upstream-interface-multicast eth0.43 --upstream-interface-fcc eth0.43 --upstream-interfa
ce-rtsp eth0.43 --external-m3u https://iptv.zsdc.eu.org/home/apt_iptv.m3u8 >/tmp/rtp2httpd.log 2>&1 &
  # 记录日志
  logger -st "($(basename "$0"))" $$ "rtp2httpd started($mcastInterface)"
  return 0
}

selectProxyStart() {
	startIf_rtp2httpd "$1" || startIf_udpxy "$1"
}

case "$1" in
  deconfig)
    /sbin/ifconfig $interface 0.0.0.0
    ;;
 
  bound)
    /sbin/ifconfig $interface $ip $BROADCAST $NETMASK
 
    if [ -n "$router" ] ; then
      logger -st "($(basename $0))" $$ "deleting routers"
      while route del default gw 0.0.0.0 dev $interface metric 1 >/dev/null 2>&1 ; do
        :
      done
      route del -net 182.139.0.0 netmask 255.255.0.0 gw 10.184.64.1 >/dev/null 2>&1
      route del -net 118.123.0.0 netmask 255.255.0.0 gw 10.184.64.1 >/dev/null 2>&1
      iptables -t nat -D POSTROUTING -d 182.139.0.0/16 -o $interface -j MASQUERADE >/dev/null 2>&1
      iptables -t nat -D POSTROUTING -d 118.123.0.0/16 -o $interface -j MASQUERADE >/dev/null 2>&1
 
      for i in $router ; do
        route add default gw $i dev $interface metric 1
      done
      route add -net 182.139.0.0 netmask 255.255.0.0 gw 10.184.64.1
      route add -net 118.123.0.0 netmask 255.255.0.0 gw 10.184.64.1
      iptables -t nat -A POSTROUTING -d 182.139.0.0/16 -o $interface -j MASQUERADE
      iptables -t nat -A POSTROUTING -d 118.123.0.0/16 -o $interface -j MASQUERADE
      logger -st "($(basename $0))" $$ "$interface $ip $BROADCAST $NETMASK  Bound OK"
      selectProxyStart $interface
    fi

    ;;

  renew)
    logger -st "($(basename $0))" $$ "$0 renew, $interface $ip ..."
    iptables -t nat -D POSTROUTING -d 182.139.0.0/16 -o $interface -j MASQUERADE >/dev/null 2>&1
    iptables -t nat -D POSTROUTING -d 118.123.0.0/16 -o $interface -j MASQUERADE >/dev/null 2>&1
    /sbin/ifconfig $interface $ip $BROADCAST $NETMASK
    iptables -t nat -A POSTROUTING -d 182.139.0.0/16 -o $interface -j MASQUERADE
    iptables -t nat -A POSTROUTING -d 118.123.0.0/16 -o $interface -j MASQUERADE
    selectProxyStart $interface
    ;;

esac
 
exit 0
